# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../src/main/vscvidlistframe.h \
    ../src/main/vsclogin.h \
    ../src/main/vscuserstatus.h \
    ../src/main/vscvidlist.h \
    ../src/main/vsctoolbar.h \
    ../src/main/vscmainwindows.h \
    ../src/common/vscviditeminf.h \
    ../src/common/vscvidtreeinf.h \
    ../src/common/switchbutton.h \
    ../src/common/vscvidinf.h \
    ../src/common/viditem/vscviditemcam.h \
    ../src/common/viditem/vscviditemvidstor.h \
    ../src/common/vidtree/vscvidtreecam.h \
    ../src/live/vscview.h \
    ../src/live/vscvidlive.h \
    ../src/config/vscvidtreeconf.h \
    ../src/config/vidclientsetting.h \
    ../src/config/vscvidconfig.h \
    ../src/config/viditem/vscviditemaddcam.h \
    ../src/config/viditem/vscviditemaddstor.h \
    ../src/config/viditem/vscviditemcamconf.h \
    ../src/config/viditem/vscviditemclientconf.h \
    ../src/config/viditem/vscviditemdiskconf.h \
    ../src/config/viditem/vscviditemstorconf.h \
    ../src/config/vidstor/vidstoradd.h \
    ../src/config/vidstor/vidcamadd.h \
    ../src/config/vidstor/vidstorsetting.h \
    ../src/config/vidstor/vidcamsetting.h \
    ../src/config/vidstor/storsetting/vscstorversion.h \
    ../src/config/vidstor/storsetting/vscstorlicense.h \
    ../src/config/vidstor/storsetting/vscstoruser.h \
    ../src/config/vidstor/disksetting/vschddedit.h \
    ../src/config/vidstor/disksetting/vschddoneedit.h \
    ../src/config/vidstor/camsetting/vsccaminfo.h \
    ../src/config/vidstor/camsetting/vsccamrec.h \
    ../src/config/clientsetting/vscversion.h \
    ../src/config/clientsetting/vsclanguage.h \
    ../src/config/clientsetting/vsclicense.h \
    ../src/config/clientsetting/vscuser.h \
    ../src/playback/vscvidpb.h \
    ../../include/oapi/oapic.hpp \
    ../../include/oapi/oapicimpl.hpp \
    ../../include/oapi/oapicmn.hpp \
    ../../include/oapi/oapiproto.hpp \
    ../../include/oapi/oapisimpl.hpp \
    ../../include/oapi/oapis.hpp \
    ../../include/config/clientconfdb.hpp \
    ../../include/config/clientconfdbimpl.hpp \
    ../../include/config/conf.hpp \
    ../../include/config/confdb.hpp \
    ../../include/config/confdbimpl.hpp \
    ../../include/config/sysdb.hpp \
    ../../include/config/vidconf.pb.h \
    ../../include/client/clientfactoryimpl.hpp \
    ../../include/client/storclientimpl.hpp \
    ../../include/client/storcmn.hpp \
    ../../include/client/storfactoryimpl.hpp \
    ../../include/client/storstreamimpl.hpp \
    ../../include/client/storsyncinfimpl.hpp \
    ../../include/client/clientfactory.hpp \
    ../../include/client/storclient.hpp \
    ../../include/client/storfactory.hpp \
    ../../include/client/storstream.hpp \
    ../../include/client/storsyncinf.hpp
SOURCES += ../src/main/main.cpp \
    ../src/main/vsclogin.cpp \
    ../src/main/vscmainwindows.cpp \
    ../src/main/vsctoobar.cpp \
    ../src/main/vscuserstatus.cpp \
    ../src/main/vscvidlist.cpp \
    ../src/main/vscvidlistframe.cpp \
    ../src/common/switchbutton.cpp \
    ../src/common/vscvidinf.cpp \
    ../src/common/vscviditeminf.cpp \
    ../src/common/vscvidtreeinf.cpp \
    ../src/common/viditem/vscviditemcam.cpp \
    ../src/common/viditem/vscviditemvidstor.cpp \
    ../src/common/vidtree/vscvidtreecam.cpp \
    ../src/live/vscvidlive.cpp \
    ../src/live/vscview.cpp \
    ../src/config/vidclientsetting.cpp \
    ../src/config/vscvidconfig.cpp \
    ../src/config/vscvidtreeconf.cpp \
    ../src/config/viditem/vscviditemaddcam.cpp \
    ../src/config/viditem/vscviditemaddstor.cpp \
    ../src/config/viditem/vscviditemcamconf.cpp \
    ../src/config/viditem/vscviditemclientconf.cpp \
    ../src/config/viditem/vscviditemdiskconf.cpp \
    ../src/config/viditem/vscviditemstorconf.cpp \
    ../src/config/vidstor/vidcamadd.cpp \
    ../src/config/vidstor/vidcamsetting.cpp \
    ../src/config/vidstor/vidstoradd.cpp \
    ../src/config/vidstor/vidstorsetting.cpp \
    ../src/config/vidstor/storsetting/vscstorlicense.cpp \
    ../src/config/vidstor/storsetting/vscstoruser.cpp \
    ../src/config/vidstor/storsetting/vscstorversion.cpp \
    ../src/config/vidstor/disksetting/vschddedit.cpp \
    ../src/config/vidstor/disksetting/vschddoneedit.cpp \
    ../src/config/vidstor/camsetting/vsccaminfo.cpp \
    ../src/config/vidstor/camsetting/vsccamrec.cpp \
    ../src/config/clientsetting/vsclanguage.cpp \
    ../src/config/clientsetting/vsclicense.cpp \
    ../src/config/clientsetting/vscuser.cpp \
    ../src/config/clientsetting/vscversion.cpp \
    ../src/playback/vscvidpb.cpp
FORMS += ../src/main/vscmainwindows.ui \
    ../src/main/vsctoolbar.ui \
    ../src/main/vscvidlist.ui \
    ../src/main/vsclogin.ui \
    ../src/main/vscuserstatus.ui \
    ../src/live/vscview.ui \
    ../src/config/vidclientsetting.ui \
    ../src/config/vidstor/vidstoradd.ui \
    ../src/config/vidstor/vidcamadd.ui \
    ../src/config/vidstor/vidstorsetting.ui \
    ../src/config/vidstor/vidcamsetting.ui \
    ../src/config/vidstor/storsetting/vscstorversion.ui \
    ../src/config/vidstor/storsetting/vscstorlicense.ui \
    ../src/config/vidstor/storsetting/vscstoruser.ui \
    ../src/config/vidstor/disksetting/vschddedit.ui \
    ../src/config/vidstor/disksetting/vschddoneedit.ui \
    ../src/config/vidstor/camsetting/vsccaminfo.ui \
    ../src/config/vidstor/camsetting/vsccamrec.ui \
    ../src/config/clientsetting/vscversion.ui \
    ../src/config/clientsetting/vsclanguage.ui \
    ../src/config/clientsetting/vsclicense.ui \
    ../src/config/clientsetting/vscuser.ui
TRANSLATIONS += ../main/translations/opencvr_zh.ts
RESOURCES += ../src/main/vscmainwindows.qrc

