/* soapNotificationConsumerBindingProxy.h
   Generated by gSOAP 2.7.17 from onvif.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapNotificationConsumerBindingProxy_H
#define soapNotificationConsumerBindingProxy_H
#include "soapH.h"

class SOAP_CMAC NotificationConsumerBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'NotificationConsumerBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	NotificationConsumerBindingProxy();
	/// Constructor with copy of another engine state
	NotificationConsumerBindingProxy(const struct soap&);
	/// Constructor with engine input+output mode control
	NotificationConsumerBindingProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	NotificationConsumerBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~NotificationConsumerBindingProxy();
	/// Initializer used by constructors
	virtual	void NotificationConsumerBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(char *wsa__MessageID, struct wsa__Relationship *wsa__RelatesTo, struct wsa__EndpointReferenceType *wsa__From, struct wsa__EndpointReferenceType *wsa__ReplyTo, struct wsa__EndpointReferenceType *wsa__FaultTo, char *wsa__To, char *wsa__Action, struct _wsse__Security *wsse__Security, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service one-way send operation 'send_Notify' (returns error code or SOAP_OK)
	virtual	int send_Notify(_wsnt__Notify *wsnt__Notify);
	/// Web service one-way receive operation 'recv_Notify' (returns error code or SOAP_OK);
	virtual	int recv_Notify(struct __ns6__Notify&);
	/// Web service receive of HTTP Accept acknowledgment for one-way send operation 'send_Notify' (returns error code or SOAP_OK)
	virtual	int recv_Notify_empty_response() { return soap_recv_empty_response(this); }
	/// Web service one-way synchronous send operation 'Notify' with HTTP Accept/OK response receive (returns error code or SOAP_OK)
	virtual	int Notify(_wsnt__Notify *wsnt__Notify) { if (send_Notify(wsnt__Notify) || soap_recv_empty_response(this)) return this->error; return SOAP_OK; }
};
#endif
